name: M-Phi4-10L
target:
- layers.11
- layers.13
- layers.17
- layers.21
- layers.22
- layers.23
- layers.24
- layers.25
- layers.27
- layers.29
- layers.8
threshold: 0.1
level: layer
model_name: microsoft/Phi-4-mini-reasoning
base_model_name: microsoft/Phi-4-mini-instruct
