name: M-Phi4-5M
target:
- layers.10.self_attn
- layers.11.mlp
- layers.11.self_attn
- layers.12.self_attn
- layers.13.self_attn
- layers.17.mlp
- layers.17.self_attn
- layers.19.mlp
- layers.21.mlp
- layers.22.mlp
- layers.23.mlp
- layers.23.self_attn
- layers.24.mlp
- layers.25.mlp
- layers.25.self_attn
- layers.27.mlp
- layers.27.self_attn
- layers.28.mlp
- layers.29.self_attn
- layers.3.mlp
- layers.5.mlp
- layers.7.mlp
- layers.7.self_attn
- layers.8.mlp
- layers.9.mlp
threshold: 0.05
level: module
model_name: microsoft/Phi-4-mini-reasoning
base_model_name: microsoft/Phi-4-mini-instruct
