name: M-Phi4-5L
target:
- layers.10
- layers.11
- layers.12
- layers.13
- layers.17
- layers.19
- layers.21
- layers.22
- layers.23
- layers.24
- layers.25
- layers.27
- layers.28
- layers.29
- layers.3
- layers.5
- layers.7
- layers.8
- layers.9
threshold: 0.05
level: layer
model_name: microsoft/Phi-4-mini-reasoning
base_model_name: microsoft/Phi-4-mini-instruct
