name: M1-Phi4-10L
target:
- layers.1
- layers.11
- layers.12
- layers.13
- layers.17
- layers.2
- layers.21
- layers.22
- layers.23
- layers.24
- layers.25
- layers.27
- layers.29
- layers.3
- layers.30
- layers.31
- layers.6
- layers.8
- layers.9
threshold: 0.1
level: layer
model_name: microsoft/Phi-4-mini-reasoning
base_model_name: microsoft/Phi-4-mini-instruct
